version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    build: .
    command: uvicorn tasks:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - redis
  celery_worker-01:
    container_name: celery_worker-01
    build: .
    command: celery -A celery_worker worker --pool=solo --loglevel=info --concurrency 1
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
  celery_worker-02:
    container_name: celery_worker-02
    build: .
    command: celery -A celery_worker worker --pool=solo --loglevel=info --concurrency 1
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
  flower:
    container_name: flower
    build: .
    command: celery -A celery_worker flower --port=5555
    ports:
      - 5556:5555
    depends_on:
      - app
      - redis
      - celery_worker-01
      - celery_worker-02
